### ISSUE TITLE
Add a dataset with multiple different models

### ISSUE THREAD

**Issue by srush** [HendrikStrobelt/LSTMVis#28]
From the comments

> It is good to see the hidden state dynamics can reflect some patterns corresponding to the range of inputs. But IMO, a more important thing is to understand the advantages of LSTMs over simple RNNs. For example, at first we can compare the different hidden dynamics between a LSTM and a simple RNN, to justify our hypothesis that a LSTM can remember the longer dependencies than a SRN. Then we may watch the behavior of the input/output/forget gates to help us understanding why this could happen.
> 
> Sure, this is a good suggestion. Maybe we can add one shared dataset with a simple RNN, LSTM (with gates), and a GRU. Would this let you look for the examples you are interested in?

**Comment by HendrikStrobelt** [comment]
examples: Childrenbook has GRU, 2x LSTM configs,...
