### ISSUE TITLE
Make  more generalizable

### ISSUE THREAD

**Issue by bottydim** [HendrikStrobelt/LSTMVis#31]
Hey guys,
**Fantastic project!**

As part of my research, I am looking into extending your platform outside of the NLP domain. In other words, I would like to be able to explore the activation states:
- for n-dimensional vectors rather than word ids 
- with respect to the predicted and target value
- of any RNN

Would you be interested in collaborating on something of the kind?

**Comment by HendrikStrobelt** [comment]
Hi,
Thank you very much. I think this is a very interesting request and would be happy to talk about it.
Feel free to contact me via email hendrik@strobelt.com

Thank you,
Hendrik for the LSTMVis team

**Comment by HendrikStrobelt** [comment]
will finally answer your email :) - sorry
