### ISSUE TITLE
Show class labels if available

### ISSUE THREAD

**Issue by alex-j-j** [HendrikStrobelt/LSTMVis#33]
I have a tagging task where each token has a bunch of annotations associated with it (the most important being the predicted and actual class). It would be great if the annotations could be shown below the main visualization. This ways, I could more easily see, e.g., which neurons lead to a wrong decision.

**Comment by srush** [comment]
Yes, this is a top priority for us. Hopefully we will get to it soon. (also accept pull requests :)

**Comment by alex-j-j** [comment]
I would love to help out instead of doing my work, but I have to finish soon :)

**Comment by HendrikStrobelt** [comment]
For V2: We added scripts to extract the top k predictions and they can be visualized as meta tracks in the Selection View. Please let us know if this helpful.
