### ISSUE TITLE
Is there more test datasets available (in addition to the children's book)

### ISSUE THREAD

**Issue by shusenl** [HendrikStrobelt/LSTMVis#42]
I find this work very interesting. I'm wondering if the author could release more test dataset such as the parentheses dataset.

Currently, the only public test data (apart from the live service) is the children's book.

**Comment by HendrikStrobelt** [comment]
With V2 we added a very small parens dataset (see front page). We also added a workflow for tensorflow if you prefer python-based frameworks. :)
