### ISSUE TITLE
Python module helper_functions is missing

### ISSUE THREAD

**Issue by dnieuw** [HendrikStrobelt/LSTMVis#49]
Dear developers,
I ran the "install" instructions from the main page and downloaded the parens data as a test.
However, I get the following error, indicating a missing module:

`
Traceback (most recent call last):
  File "lstm_server.py", line 8, in <module>
    from lstmdata.data_handler import LSTMDataHandler
  File "/home/dnieuwenhuijse/Software/LSTMVis/lstmdata/data_handler.py", line 11, in <module>
    import helper_functions as hf
ModuleNotFoundError: No module named 'helper_functions'
`

I couldn't find the module on your github repo either, so I am guessing that you have removed the module from your repo by accident?

Kind regards,

David

**Comment by sebastianGehrmann** [comment]
Hi @dnieuw, I cannot replicate this error and can see module [here](https://github.com/HendrikStrobelt/LSTMVis/blob/master/lstmdata/helper_functions.py)
Can you try again after cloning the repository from scratch? If it still doesn't work, can you let me know which python version you are on and your installed packages so I can try and replicate the error?

**Comment by dnieuw** [comment]
Hi @sebastianGehrmann, 

I have re-cloned the repo and have found the module, however, lstm_server.py does not seem to be able to import it. I am able to import the module myself when running python from the lstmdata folder itself, so that seems fine. I have installed the required packages via Anaconda, see the complete enviroment:

_license                  1.1                      py36_1  
alabaster                 0.7.10                   py36_0  
anaconda                  4.4.0               np112py36_0  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.2                    py36_0  
anaconda-project          0.6.0                    py36_0  
asn1crypto                0.22.0                   py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3.2               np112py36_0  
babel                     2.4.0                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.6.0                    py36_0  
biopython                 1.68                np112py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_1  
boto                      2.46.1                   py36_0  
bottleneck                1.2.1               np112py36_0  
cairo                     1.14.8                        0  
cffi                      1.10.0                   py36_0  
chardet                   3.0.3                    py36_0  
click                     6.7                      py36_0  
clickclick                1.2.1                    py36_0    conda-forge
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.9                    py36_0  
colormath                 2.1.1                    py36_0    conda-forge
conda                     4.3.22                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
connexion                 1.1.10                   py36_0    conda-forge
contextlib2               0.5.5                    py36_0  
cryptography              1.8.1                    py36_0  
cudatoolkit               7.5                           0  
cudnn                     5.1                           0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cymem                     1.31.2                   py36_0    conda-forge
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.3                   py36_1  
datashape                 0.5.4                    py36_0  
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
dill                      0.2.6                    py36_0    conda-forge
distributed               1.16.3                   py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_1  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
flask                     0.12.2                   py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
ftfy                      4.4.2                    py36_0    conda-forge
future                    0.16.0                   py36_0    conda-forge
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
greenlet                  0.4.12                   py36_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np112py36_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
idna                      2.5                      py36_0  
imagesize                 0.7.1                    py36_0  
inflection                0.3.1                    py36_0  
ipykernel                 4.6.1                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                   py36_2  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
keras                     2.0.2                    py36_0  
keras-gpu                 2.0.2                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libgpuarray               0.6.4                         0  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libprotobuf               3.2.0                         0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         3  
libtool                   2.4.2                         0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
lzstring                  1.0.3                    py36_0    conda-forge
mako                      1.0.6                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.2               np112py36_0  
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
msgpack-python            0.4.8                    py36_0  
multipledispatch          0.4.9                    py36_0  
multiqc                   1.0                      py36_4    bioconda
murmurhash                0.26.4                   py36_0    conda-forge
navigator-updater         0.1.0                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
networkx                  1.11                     py36_0  
nltk                      3.2.3                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
numba                     0.33.0              np112py36_0  
numexpr                   2.6.2               np112py36_0  
numpy                     1.12.1                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
openpyxl                  2.4.7                    py36_0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py36_0  
pandas                    0.20.1              np112py36_0  
pandocfilters             1.4.1                    py36_0  
pango                     1.40.3                        1  
partd                     0.3.8                    py36_0  
path.py                   10.3.1                   py36_0  
pathlib2                  2.2.1                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.1.1                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
plac                      0.9.6                    py36_0  
ply                       3.10                     py36_0  
preshed                   1.0.0                    py36_0    conda-forge
prompt_toolkit            1.0.14                   py36_0  
protobuf                  3.2.0                    py36_0  
psutil                    5.2.2                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.33                   py36_0  
pycosat                   0.6.2                    py36_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_6  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pygpu                     0.6.4                    py36_1  
pylint                    1.6.4                    py36_1  
pyodbc                    4.0.16                   py36_0  
pyopenssl                 17.0.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np112py36_0  
pytest                    3.0.7                    py36_0  
python                    3.6.1                         2  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
pywavelets                0.5.2               np112py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         4  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
readline                  6.2                           2  
regex                     2017.06.23               py36_0    conda-forge
requests                  2.14.2                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np112py36_0  
scikit-learn              0.18.1              np112py36_1  
scipy                     0.19.0              np112py36_0  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
simplejson                3.8.1                    py36_0    bioconda
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sortedcollections         0.5.3                    py36_0  
sortedcontainers          1.5.7                    py36_0  
spacy                     1.9.0               np112py36_0    conda-forge
spectra                   0.0.7                    py36_0    conda-forge
sphinx                    1.5.6                    py36_0  
spyder                    3.1.4                    py36_0  
sqlalchemy                1.1.9                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np112py36_0  
swagger-spec-validator    2.1.0                    py36_0    conda-forge
sympy                     1.0                      py36_0  
tblib                     1.3.2                    py36_0  
tensorflow                1.1.0               np112py36_0  
tensorflow-gpu            1.1.0               np112py36_0  
termcolor                 1.1.0                    py36_1    conda-forge
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
theano                    0.9.0                    py36_0  
thinc                     6.5.2               np112py36_0    conda-forge
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.5.1                    py36_0  
tqdm                      4.15.0                   py36_0    conda-forge
traitlets                 4.3.2                    py36_0  
typing                    3.6.1                    py36_0    conda-forge
ujson                     1.35                     py36_0  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.4                         0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.12.2                   py36_0  
wheel                     0.29.0                   py36_0  
whoosh                    2.7.4                    py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.10                  py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0  
zict                      0.1.2                    py36_0  
zlib                      1.2.8                         3

**Comment by sebastianGehrmann** [comment]
Hey, unfortunately LSTMVis operates on python 2.7 and this is the reason for your error. Ensuring python 3 compatibility would unfortunately require a complete rewrite and is not feasible without significant effort. 
Can you try running it with python 2.7? It should all work then.

**Comment by dnieuw** [comment]
Thanks, it works using a Python 2.7 environment on anaconda!
