### ISSUE TITLE
ModuleNotFoundError: No module named 'helper_functions'

### ISSUE THREAD

**Issue by blindfish** [HendrikStrobelt/LSTMVis#51]
When I run this execution:
`python lstm_server.py -dir data`

Getting this error below. Ideas on how to fix?

```
Traceback (most recent call last):
  File "lstm_server.py", line 8, in <module>
    from lstmdata.data_handler import LSTMDataHandler
  File "/home/user/Documents/GitHub/LSTMVis/lstmdata/data_handler.py", line 11, in <module>
    import helper_functions as hf
ModuleNotFoundError: No module named 'helper_functions'
```

**Comment by WillieMaddox** [comment]
I had the same problem trying to run under Python 3.6.2.  

Run it in a Python 2.7 environment and you'll be good to go.

**Comment by sebastianGehrmann** [comment]
Indeed, the server is not compatible with python 3 as of yet. Sorry about that!
