### ISSUE TITLE
KeyError: "Unable to open object ..." - lstm.yml

### ISSUE THREAD

**Issue by sachn1** [HendrikStrobelt/LSTMVis#61]
I generated the three files required for running the lstm server. But the main thing which I don't find in the documentation of the tool is what exactly is the **path** mentioned in lstm yaml file. I'm constantly getting errors in the line path! 

The image below shows my yaml file:
![image](https://user-images.githubusercontent.com/25841911/76415303-f5fa9e80-63be-11ea-9a61-ec4fca295e9f.png)

Running the server shows the following error:
![image](https://user-images.githubusercontent.com/25841911/76415444-36f2b300-63bf-11ea-9733-7a218f117064.png)

My network only consists of 1 hidden layer. I'm not sure whether I understood that part of visualization right!

Later I commented out those two lines in **states** and ran the server again.
![image](https://user-images.githubusercontent.com/25841911/76415738-c5673480-63bf-11ea-922c-eeb10e01ebda.png)

which shows:
![image](https://user-images.githubusercontent.com/25841911/76415815-ec256b00-63bf-11ea-9eb6-b3d4a62ecef7.png)

Could someone help me out as I don't find enough documentation on what does **path** exactly meant to do here?

**Comment by gj0706** [comment]
I think the path is the name(key) of the dataset in your HDF5 file.  Here is what it looks like when I read the example file:
<img width="995" alt="Screen Shot 2020-03-11 at 3 29 35 PM" src="https://user-images.githubusercontent.com/32847054/76461008-115cae00-63ad-11ea-83ae-9af88c738124.png">
So you may need to change it if you use your own data. Just read your HDF5 file and find the corresponding name. 

By the way, are you able to run the local server? It shows ' 403 Fobbiden' occasionally and I don't know why.

**Comment by sachn1** [comment]
Thanks @gj0706! That did the trick!
