### ISSUE TITLE
Using LSTMVis on text classification. 

### ISSUE THREAD

**Issue by VenkateshDas** [HendrikStrobelt/LSTMVis#62]
I have a dataset with 627 instances and each has a label (Yes or No). This is a binary classification problem. And I am using BiLSTM network with 282 timesteps and 128 hidden units. Since it is Bidirectional, there are 256 hidden units. 

I created a space-separated txt file with all the instances in it and converted to hdf5 using the text conversion tool. I extracted the cell states of shape(282,256) from the network. I passed these files to the LSTMVis, I am only able to visualise till the position of 280 in the graph. 

How do I visualise for all the instances or words in the dataset? 

Should I provide a hdf5 file only for the amount of time steps specified in the model. For example, one input instance will have 282 as the length of the sequence ( timestep). Should my train.hdf5 file aslo have only the length of 282? 

I am finding it difficult to make useful inferences based on the output i am getting. 
<img width="720" alt="Screenshot 2020-04-21 at 8 50 15 PM" src="https://user-images.githubusercontent.com/17122430/79919540-e7c48700-842e-11ea-9451-71fab45f00fc.png">

How do i visualise for all the instances or should I do it only for the timesteps provided?

**Comment by HendrikStrobelt** [comment]
sorry for late reply -- I guess it was just using the three dots in the interface ?
